### PR TITLE
Allow the use of {{cleanAppId}} in the logs link template

### PR DESCRIPTION
**Pull request by clems4ever**
Currently, app names are not homogeneous in kibana. We need the logs
links to be templated by the appId which is the actual app ID without the
starting / and cleanAppId which is the app ID without the starting / and
with all non alpha numerical characters replaced by _.

### CODE REVIEW

**Comment by kamaradclimber** [comment]
sorry I realyy dont understand this PR. I think I'll need some explainations on Thursday :)

**Comment by clems4ever** [comment]
Sure! I'm actually not very happy with this PR anyway. You'll give us your opinion. Thanks.

**Comment by pierrecdn** [comment]
True, that's due to the way we build the logs using environment variables (in the wrapme).
Marathon itself do the opposite at some point so the best would probably be to retrieve the taskId and remove the UUID as suffix.

**Comment by clems4ever** [comment]
Hello @pierrecdn , retrieving the taskId for computing the app ID is not ok because it means the app ID needs to be computed in the UI and it is not straightforward. This is just a denormalization coming from Criteo, it should not be in the code of Marathon UI. By chance, today the app ID is prepended to the task ID but what about tomorrow?
I'm really wondering why we would not be able to put the actual app ID as it is in marathon in kibana. Same thing for task ID by the way. Is the denormalization really mandatory?

FYI, I have implemented what the other Pierre :) proposed yesterday in https://github.com/criteo-forks/marathon-ui/pull/3. Basically, we proposed to allow the user to give his own javascript function that takes the app ID as input and returns the link, such function is given in the runtimeConfig. 
But still I'm not very ok with this approach because it has a flow in term of security. An attacker hijacking the runtimeConfig would be able to inject malicious code easily in the user browser and run anything from there (retrieving cookies for example). There are mechanisms in the browser to avoid such attacks but I don't know yet if Marathon leverages them. Not very confident this would be open-sourceable anyway...

I would really prefer the simple template in the runtimeConfig and no denormalization. It would be perfect. Or, if we can't undo the denormalization easily we could add a proxy that does the denormalization before redirecting to kibana. This would be much much cleaner but add one more component to the architecture (with what it implies unfortunately...).

**Comment by pierresouchay** [comment]
@clems4ever  I don't really agree with you regarding security implications:

runtimeConfig.js is a file on the server, in the same way any JS file, so if an attacker is able to hijack this file, he would be able to change the JS code anyway, so it does not change anything on a security perspective

**Comment by clems4ever** [comment]
@pierresouchay , you are right, it's probably as hard to spoof runtimeConfig.js as main.js anyway.

**Comment by clems4ever** [comment]
I'm closing this PR in favor of #3

**Pull request closed without merging**
