### PR TITLE
[UX] By default show latest updated tasks first

### PR DESCRIPTION
**Pull request by kamaradclimber**
When going to marathon task list, are usually more interested in tasks
that started / are starting than by task that have not changed state for
a long time.

Change-Id: I7d8180903c9460ca9f17b8da9a3c3e149ff69eb1

### CODE REVIEW

**Review by clems4ever — APPROVED** [review]
LGTM

**Review by warrenseine — COMMENTED** [review]
While you’re doing this kind of changes, would you mind trying to raise the default task per page from 8 to maybe 100? So it’s easy to Ctrl+F for a specific instance?

I wasn’t able to boot the Docker container from Windows, otherwise I would have done it.

**Comment by warrenseine** [comment]
Oh! I just saw that you did in a next commit! Thank you!

**Comment by kamaradclimber** [comment]
That's exactly the purpose of my series of change @warrenseine ;)

**Pull request merged**
